/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsLessonDetailLessonIdRouteImport } from './routes/lessons/LessonDetail.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonDetailLessonIdRoute =
  LessonsLessonDetailLessonIdRouteImport.update({
    id: '/lessons/LessonDetail/$lessonId',
    path: '/lessons/LessonDetail/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons/LessonDetail/$lessonId': typeof LessonsLessonDetailLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons/LessonDetail/$lessonId': typeof LessonsLessonDetailLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons/LessonDetail/$lessonId': typeof LessonsLessonDetailLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lessons/LessonDetail/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lessons/LessonDetail/$lessonId'
  id: '__root__' | '/' | '/lessons/LessonDetail/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsLessonDetailLessonIdRoute: typeof LessonsLessonDetailLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/LessonDetail/$lessonId': {
      id: '/lessons/LessonDetail/$lessonId'
      path: '/lessons/LessonDetail/$lessonId'
      fullPath: '/lessons/LessonDetail/$lessonId'
      preLoaderRoute: typeof LessonsLessonDetailLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsLessonDetailLessonIdRoute: LessonsLessonDetailLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
